### ISSUE TITLE
活动发布/修正

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/HOP#2]
新增、编辑页面/接口共用

**Comment by jiangyuzhen** [comment]
|   字段           |  Key              | 　示例　　                                |
|:----------------:|:-----------------:|:-----------------------------------------:|
| 活动名称      | title               | `"xxx 黑客松"`                            |
| 主题关键词  | keyWord       | `“JavaScript,Node.JS”`              |
| 开始时间      | startTime      | `1494753879`（UNIX 时间戳）|
| 结束时间      | endTime       | 【同上】                                    |
| 活动地点　  |  address        | `"XX省XX市XX区XX"`               |
| 活动描述      | description　| `“XXXXXXXX”`                          |

**Comment by TechQuery** [comment]
活动信息表单（发布）—— ef0f07f

**Comment by TechQuery** [comment]
FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io@ac67ea2
