### ISSUE TITLE
参赛项目演示部署服务

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/HOP#6]
初期可直接在同一服务器部署的项目类型 ——
 - [ ] 纯 Web 前端、各平台客户端 静态文件
 - [ ] ~PHP（SQLite 数据库、不依赖非官方 C/C++ 扩展库）~
 - [ ] Node.JS（NPM 管理、SQLite 数据库、不依赖非官方 C/C++ 扩展包）

部署流程 ——
 1. 在每个项目专用的目录下 `git clone`
 2. 纯静态文件可直接通过 `//host/demo/project_x/file_y` 访问
 3. NPM 项目（不可占用 80 端口）先 `npm install  &&  npm start`，再由本站 HTTP 服务器重定向 `//host/demo/project_z/` 下的请求至其专用端口号

**Comment by demongodYY** [comment]
用什么搭HTTP服务器呢？niginx?

**Comment by demongodYY** [comment]
写成自动化脚本以达到用户一键部署吗？

**Comment by demongodYY** [comment]
我想通过浏览器发生添加项目事件，在数据库中添加待部署项目并等待。服务器本地脚本轮询数据库，发现待部署项目进行部署，并等待部署完毕后，返回部署完毕状态以及端口号到数据库。浏览器访问到部署完毕状态显示端口号。

**Comment by TechQuery** [comment]
@demongodYY 
我想基于**微服务**思想，把**项目演示部署**做成独立的 HTTP 服务，对与大前端交互的**业务后端**开放 RESTful API。

**Comment by TechQuery** [comment]
**纯 Web 前端项目** 直接用 [GitHub Pages](https://developer.github.com/v3/repos/pages/)，有后端程序的可基于 [Web Hook](https://developer.github.com/webhooks/)、[Docker](https://www.docker.com/) 实现自动部署 ——

 - https://aotu.io/notes/2016/01/07/auto-deploy-website-by-webhooks-of-github/
 - https://zhuanlan.zhihu.com/p/25078139

**Comment by TechQuery** [comment]
现已有 GitHub 生态的各类免费云服务：
1. https://vercel.com/
2. https://render.com/
3. https://fly.io/
