### ISSUE TITLE
域名、服务器租用

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/HOP#7]
### 域名注册

hackathon 英文域名还可以的就只剩下 `hackathon.studio` 了 —— https://wanwang.aliyun.com/domain/searchresult/?keyword=hackathon&suffix=.com

heikesong 拼音域名几乎都有，最好直接选个接地气的 `heikesong.cn`~

### 服务器租用

本人个人网站、外包项目 都用 [腾讯云](https://www.qcloud.com)，相比 [阿里云](https://www.aliyun.com)业务开通方便、管理系统易上手、可靠性完全满足中小开发者，性价比更高。

**Comment by DeronLee** [comment]
这里主要就是决定域名和服务器的租用么？有什么可以帮忙的？

**Comment by TechQuery** [comment]
@DeronLee 想个炫酷又方便的域名吧~

**Comment by too** [comment]
.cn 的要备案呢，想好哦。不要长了，宁愿缩写

**Comment by DeronLee** [comment]
最好不用. cn的。麻煩

**Comment by DeronLee** [comment]
freecodecamp-cd.com
freecodecamp-cd.cn
刚才查了下都没有被注册

**Comment by TechQuery** [comment]
@DeronLee 就是感觉 FreeCodeCamp 名字太长……

**Comment by DeronLee** [comment]
其實也還好啦。反正常用的都會收藏。

**Comment by TechQuery** [comment]
## 域名

@TechQuery 已为社区注册：
1. https://fcc-cd.dev/
2. https://web-conf.dev/

## 服务器

可用免费云服务：
1. Web 服务器：https://render.com/
2. 数据库服务：https://supabase.com/
